options:
  merge-default-rules: false
  formatter: html
  output-file: "linters/sass-lint.html"
  max-warnings: 50

files:
  include: "styles/**/*.s+(a|c)ss"

rules:
    border-zero:
        - 2
        - convention: "none"
    class-name-format:
        - 2
        - allow-leading-underscore: false
    declarations-before-nesting: 2
    empty-args:
        - 2
        - include: true
    extends-before-declarations: 2
    extends-before-mixins: 2
    force-attribute-nesting: 0
    force-element-nesting: 0
    force-psuedo-nesting: 0
    function-name-format:
        - 2
        - allow-leading-underscore: false
    hex-length:
        - 2
        - style: "long"
    id-name-format:
        - 2
        - allow-leading-underscore: false
    indentation:
        - 2
        - size: "tab"
    leading-zero:
        - 2
        - include: true
    mixins-before-declarations:
        - 2
        - exclude:
            - "breakpoint"
            - "mq"
    mixin-name-format:
        - 2
        - allow-leading-underscore: false
    no-color-keywords: 2
    no-css-comments: 2
    no-debug: 1
    no-important: 2
    no-invalid-hex: 2
    no-mergeable-selectors: 2
    no-misspelled-properties: 2
    no-trailing-whitespace: 2
    no-trailing-zero: 0
    no-transition-all: 0
    no-universal-selectors: 1
    no-url-domains: 2
    no-warn: 1
    one-declaration-per-line: 0
    placeholder-in-extend: 2
    placeholder-name-format:
        - 2
        - allow-leading-underscore: false
    pseudo-element: 2
    property-sort-order:
        - 2
        - order:
            - "box-sizing"
            - "content"
            - "position"
            - "display"
            - "top"
            - "bottom"
            - "left"
            - "right"
            - "z-index"
            - "width"
            - "height"
            - "clear"
            - "float"
            - "overflow"
            - "margin"
            - "margin-left"
            - "margin-top"
            - "margin-right"
            - "margin-bottom"
            - "padding"
            - "padding-left"
            - "padding-top"
            - "padding-right"
            - "padding-bottom"
            - "font-family"
            - "font-size"
            - "color"
        - ignore-custom-properties: true
    quotes:
        - 2
        - style: "double"
    shorthand-values: 2
    single-line-per-selector: 0
    space-after-bang: 1
    space-after-colon: 1
    space-after-comma: 1
    space-around-operator: 1
    space-before-bang: 1
    space-before-brace: 1
    space-before-colon: 0
    space-between-parens: 1
    trailing-semicolon: 2
    url-quotes: 2
    variable-for-property: 0
    variable-name-format:
        - 2
        - allow-leading-underscore: false
    zero-unit: 2
